# -*- coding: utf-8 -*-
"""2025007855-RecursiveDFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XSyNaZ1DRFPMuDNgNdo4t94rzfDrXyO

Recursive DFS
"""

def dfs_recursive(graph, node, visited =None ):
    if visited is None:
      visited = set()
    visited.add(node)
    print(node, end=' ')

    for neighbor in graph[node]:
      if neighbor not in visited:
        dfs_recursive(graph, neighbor, visited)
    return visited
graph = {
         'A':['B','C'],
         'B':['D','E'],
         'C':['F'],
         'D':[],
         'E':['F'],
         'F':[]
}
print("Recursive DFS traversal from node A:")
dfs_recursive(graph,'A')
#OUTPUT:Recursive DFS traversal from node A:
# A B D E F C 
# {'A', 'B', 'C', 'D', 'E', 'F'}
